config/routes.rb
Jokes::Application.routes.draw do
  get "jokes/new"

  get "jokes/index"

  get "jokes/show"

	resources :jokes

  root :to => 'jokes#index'

end

app/models/joke.rb
class Joke < ActiveRecord::Base
	has_one :score
  attr_accessible :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  def new
		@joke = Joke.new
  end

  def index
		@jokes = Joke.all
  end

	def create
		@joke = Joke.new(params[:joke])
		if @joke.save
			flash[:success] = 'saved success!'
		else
			flash[:error] = 'error! didnt save'
		end
		redirect_to new_joke_path
		
		#redirect_to jokes_path
	end

	def update
		@joke = Joke.find_by_id(params[:id])
		@joke.increment!(params[:vote])
		redirect_to jokes_path
	end

	def destroy
		@joke = Joke.find(params[:id])
		@joke.delete
		redirect_to jokes_path
	end

  def show
		@joke = Joke.find(params[:id])
  end

	def edit
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/jokes/index.html.erb
<h1>
	Jokes
</h1>
<br>

<% @jokes.each do |j| %>
<div class="joke-container">
<table class="joke">
    <tr class="joke">
<tr>
	<td colspan='3'>
		<%= j.content %>
	</td>
</tr>
<tr>
    <td>
        <br>
    </td>
</tr>
<tr>
	
	<td>
	<%= j.up  %> <%= link_to 'like', joke_path(j.id, :vote=>'up'), :method=>'PUT' %>
	</td>
	<td>
	<%= j.down %> <%= link_to 'dislike', joke_path(j.id, :vote=>'down'), :method=>'PUT' %>
	</td>
	<td class="pull-right">
		<%= link_to 'x', joke_path(j.id), :method => 'DELETE',:confirm=>'Are you sure you want to delete?' %>
	</td>
</tr>
</tr>
<tr>
</tr>
</table>
</div>
<% end %>

app/views/jokes/new.html.erb
<h1>Jokes#new</h1>
<p>Find me in app/views/jokes/new.html.erb</p>

<% if flash[:success] %>
<%= flash[:success] %>
<% else %>
<%= flash[:error] %>
<% end %>

<%= form_for @joke do |f|  %>
<%= f.text_area :content %> 
<%= f.submit %>
<% end %>

app/views/jokes/show.html.erb
<h1>Jokes#show</h1>
<p>Find me in app/views/jokes/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jokes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">

<%= yield %>

    </div>
</body>
</html>